"""Private contracts shared by Workspace Feishu deployable components."""

from feishu_protocol.capabilities import (
    DOCX_MEDIA_READ_CAPABILITY,
    DOCX_READ_CAPABILITY,
    SHEETS_EXPORT_VERIFY_CAPABILITY,
    SHEETS_MANAGED_WRITE_CAPABILITY,
    SHEETS_MEDIA_READ_CAPABILITY,
    SHEETS_READ_CAPABILITY,
    SHEETS_TYPED_VALUES_WRITE_CAPABILITY,
    SUPPORTED_CAPABILITIES,
    WIKI_CHILD_LIST_CAPABILITY,
    WIKI_NODE_CREATE_CAPABILITY,
    WIKI_NODE_READ_CAPABILITY,
)
from feishu_protocol.client import LocalClientIdentity
from feishu_protocol.leases import LeaseDelivery, LeaseRequest

__all__ = [
    "DOCX_MEDIA_READ_CAPABILITY",
    "DOCX_READ_CAPABILITY",
    "LeaseDelivery",
    "LeaseRequest",
    "LocalClientIdentity",
    "SHEETS_EXPORT_VERIFY_CAPABILITY",
    "SHEETS_MANAGED_WRITE_CAPABILITY",
    "SHEETS_MEDIA_READ_CAPABILITY",
    "SHEETS_READ_CAPABILITY",
    "SHEETS_TYPED_VALUES_WRITE_CAPABILITY",
    "SUPPORTED_CAPABILITIES",
    "WIKI_CHILD_LIST_CAPABILITY",
    "WIKI_NODE_CREATE_CAPABILITY",
    "WIKI_NODE_READ_CAPABILITY",
]
