"""Stable semantic capability identifiers shared by Feishu components."""

DOCX_READ_CAPABILITY = "feishu.docx.read"
WIKI_NODE_READ_CAPABILITY = "feishu.wiki.node.read"
WIKI_CHILD_LIST_CAPABILITY = "feishu.wiki.child.list"
WIKI_NODE_CREATE_CAPABILITY = "feishu.wiki.node.create"
DOCX_MEDIA_READ_CAPABILITY = "feishu.docx.media.read"
SHEETS_READ_CAPABILITY = "feishu.sheets.read"
SHEETS_MEDIA_READ_CAPABILITY = "feishu.sheets.media.read"
SHEETS_MANAGED_WRITE_CAPABILITY = "feishu.sheets.managed_sheet.write"
SHEETS_TYPED_VALUES_WRITE_CAPABILITY = "feishu.sheets.typed_values.write"
SHEETS_EXPORT_VERIFY_CAPABILITY = "feishu.sheets.export.verify"

SUPPORTED_CAPABILITIES = (
    DOCX_MEDIA_READ_CAPABILITY,
    DOCX_READ_CAPABILITY,
    SHEETS_EXPORT_VERIFY_CAPABILITY,
    SHEETS_MANAGED_WRITE_CAPABILITY,
    SHEETS_MEDIA_READ_CAPABILITY,
    SHEETS_READ_CAPABILITY,
    SHEETS_TYPED_VALUES_WRITE_CAPABILITY,
    WIKI_CHILD_LIST_CAPABILITY,
    WIKI_NODE_CREATE_CAPABILITY,
    WIKI_NODE_READ_CAPABILITY,
)
